# Generated by Django 6.0 on 2025-12-26 21:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('tx_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Transaction')),
                ('client_reference', models.CharField(help_text='Référence de commande fournie par le client', max_length=100, verbose_name='Référence Client')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('currency', models.CharField(choices=[('XOF', 'Franc CFA'), ('USD', 'Dollar US'), ('EUR', 'Euro')], default='XOF', max_length=3, verbose_name='Devise')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Succès'), ('FAILED', 'Échec'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('secret_hash', models.CharField(editable=False, max_length=64, verbose_name='Hash Secret')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Client')),
                ('callback_url', models.URLField(blank=True, help_text='URL où envoyer la notification WebHook', null=True, verbose_name='URL de Callback')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('failure_reason', models.TextField(blank=True, null=True, verbose_name="Raison de l'échec")),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client_reference'], name='paysim_tran_client__198135_idx'), models.Index(fields=['status', 'created_at'], name='paysim_tran_status_d8a041_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebHookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL Destination')),
                ('payload', models.JSONField(verbose_name='Contenu du Payload')),
                ('signature', models.CharField(max_length=64, verbose_name='Signature Envoyée')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='Code HTTP de Réponse')),
                ('response_body', models.TextField(blank=True, null=True, verbose_name='Corps de la Réponse')),
                ('success', models.BooleanField(default=False, verbose_name="Succès de l'Envoi")),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'Envoi")),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='paysim.transaction')),
            ],
            options={
                'verbose_name': 'Log WebHook',
                'verbose_name_plural': 'Logs WebHook',
                'ordering': ['-sent_at'],
            },
        ),
    ]
